langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.siliconflow.cn/v1
      api-key: ${SILICON_API_KEY}
      model-name: Qwen/Qwen3-8B
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.siliconflow.cn/v1
      api-key: ${SILICON_API_KEY}
      model-name: Qwen/Qwen3-8B
      log-requests: true
      log-responses: true
      timeout: PT1M
    embedding-model:
      base-url: https://api.siliconflow.cn/v1
      api-key: ${SILICON_API_KEY}
      model-name: BAAI/bge-m3
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379
  # MySQL 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quickplan_ai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Xu821120
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

# MyBatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
